// <auto-generated />
namespace Ineval.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _191020211421 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_191020211421));
        
        string IMigrationMetadata.Id
        {
            get { return "202110191921517_191020211421"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
