// <auto-generated />
namespace Ineval.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _071220211913 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_071220211913));
        
        string IMigrationMetadata.Id
        {
            get { return "202112080013334_071220211913"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
