// <auto-generated />
namespace Ineval.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _020920212331 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_020920212331));
        
        string IMigrationMetadata.Id
        {
            get { return "202109030431258_020920212331"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
